name: Python Syntax Check

on:
  pull_request:  #
  push:
    branches:
      - master   

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Adjust as needed

      - name: Syntax check all Python files
        run: |
          echo "Checking Python syntax..."
          find . -name "*.py" -exec python -m py_compile {} +
