name: Lint Python Code

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  lint-python:
    name: Run Python Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Super Linter
        uses: super-linter/super-linter/slim@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_PYTHON: true
          VALIDATE_ALL_CODEBASE: true
          DISABLE_ERRORS: false
